### PR TITLE
Set curl option follow location to true

### PR DESCRIPTION
**Pull request by olleharstedt**
This is to allow redirect from http to https.

### CODE REVIEW

**Comment by olleharstedt** [comment]
Notice that the returned string is slightly different when redirect from HTTP to HTTPS is used. Instead of just a GIF, you will get

```
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 21 Feb 2018 09:31:38 GMT
Content-Type: image/gif
Transfer-Encoding: chunked
Connection: keep-alive

GIF89a\000\000\000\000\000\000\000\000\000\000!�\000\000\000\000,\000\000\000\000\000\000\000D\000;
```

**Comment by tsteur** [comment]
Awesome thank you 👍  I checked it should work for all PHP versions.

One possible thing to think about: What do we do when there is a location redirect and it is a POST request? The POST request would not re-submit the data AFAIK and the tracking request would not work. Maybe for now we enable it only when `$method === 'GET'`?

This is the case in all requests but bulk tracking. For POST requests I wonder if we should later rather implement to check if there is a location header in the response, and if so POST the request to that URL?

**Comment by tsteur** [comment]
@olleharstedt  are you still working on this PR? Could we add the follow option maybe only for GET requests?

**Comment by olleharstedt** [comment]
Hi! Was on vacation. Yes, I can modify the PR to include the option only for GET requests.

**Comment by olleharstedt** [comment]
New PR here: https://github.com/matomo-org/matomo-php-tracker/pull/46

**Pull request closed without merging**
