### PR TITLE
Allow switching between request methods and post token by default

### LINKED ISSUE #43: POST when using PiwikTracker instead of GET to prevent token_auth showing in access_log
**Per:**
_Originally posted by @c-prompt in https://github.com/matomo-org/matomo/issues/7349#issuecomment-478694584_

> I suggest you create an issue in the Matomo PHP Tracker for this: https://github.com/matomo-org/matomo-php-tracker/
> For the archiving there is https://github.com/matomo-org/matomo/issues/14190
> _Originally posted by @tsteur in https://github.com/matomo-org/matomo/issues/7349#issuecomment-478706973_

### PR DESCRIPTION
**Pull request by tsteur**
follow up from https://github.com/matomo-org/matomo-php-tracker/pull/71/files
to fix #43 

I haven't fully tested it. If someone could continue and test it this would be great. 

Bulk requests would keep behaving the same. All other requests should behave like this:

* You can now force `POST` of all requests. When set, all parameters will be posted. This can be useful if there's a problem on the webserver re URL length or the requests are very long.
* By default we still use GET
   * Unless a token auth is specified. In this case we use POST but we only POST the token, nothing else. This way log replay will still be possible.
      * Unless you force `GET` request method. Then token_auth will still be sent using `GET` which can be useful if you are having redirect issues for example.

### CODE REVIEW

**Comment by silvershadowcc** [comment]
I used the following script.

```
<?php
$path = __DIR__ . '/data.txt';

file_put_contents($path, json_encode(array('get' => $_GET, 'post' => $_POST), JSON_PRETTY_PRINT), FILE_APPEND);
```

The token was set for every request.

I got as output:
setRequestMethodNonBulk('POST') -> Only POST, but token is missing
setRequestMethodNonBulk('GET') -> Only GET, token included
setRequestMethodNonBulk() not used -> Only GET, but token is missing (in both GET and POST)

Expected behaviour:
setRequestMethodNonBulk('POST') -> Only POST, token included
setRequestMethodNonBulk('GET') -> Only GET. token included
setRequestMethodNonBulk() not used -> GET, but token through POST

**Comment by tsteur** [comment]
Thanks @silvershadowcc I've tested it now as well and fixed it. In my case it worked nicely.

**Comment by silvershadowcc** [comment]
I will test it again this weekend. Also with redirects.

**Comment by silvershadowcc** [comment]
In my case it works nicely as well. Got the results as stated in the expected behaviour above.

Redirecting also works fine (using cURL). I changed the code to test this though, since I wasn't sure whether `if (defined('CURL_REDIR_POST_ALL'))` should've been defined in the file or PHP config. I think this check could be skipped to make it default behaviour to follow redirects for POST parameters, especially now that the token_auth is silently sent as POST parameter by default.

I did find a typo for which I have made a PR in your branch. This needs to be fixed in order for redirects to work.

**Comment by tsteur** [comment]
@sgiehl technically, this one could break something so would need to release ideally a `3.0.0` but considering Matomo 1 is still including `1.X` in https://github.com/matomo-org/matomo/blob/3.14.1-b1/composer.json#L47 maybe it be fine to release a 2.1 version afterwards? Can also make it 3.0 I'm not quite sure what the policy is so far.

Technically, something could break because if a token_auth is used, and the user is using eg `http://example.com/matomo.php` as tracking API, and this URL redirects to `https://example.com/matomo.php` and not `curl` is used (or an old PHP version is used), then it might execute the tracking request without the posted tracking parameter. So it's quite an edge case but problems could still happen. Wonder if we would simply release a 3.0 afterwards?

We POST tokens by default to have it secure by default.

**Comment by sgiehl** [comment]
@tsteur version 2.0 was only released for the new package name. Even though all versions are now available on both names, as we are using the same repo 🤷 
Should those changes be included for Matomo 3.x? If not we could move it to 4.x-dev branch and release a new major version once Matomo 4 beta will be finished...

**Comment by tsteur** [comment]
They shouldn't be included in 3.x.
Could release a new major version before the beta? or some beta version like 3.0-be1? Then we could already include it in first Matomo 4 beta?

**Comment by sgiehl** [comment]
Matomo 4 currently uses the 4.x-dev branch of this repo: https://github.com/matomo-org/matomo/blob/4.x-dev/composer.json#L38

**Comment by tsteur** [comment]
Thanks for your help @silvershadowcc very appreciated

**Pull request merged**
