### PR TITLE
cURL error should throw an exception to ease debug

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by tsteur** [comment]
@mattab any thoughts here?

**Comment by tsteur** [comment]
ping @mattab 
I reckon this could break BC.

**Comment by mattab** [comment]
Thanks for the PR @kylekatarnls 
@tsteur added this PR to a new meta issue at: https://github.com/matomo-org/matomo/issues/14746

**Comment by sgiehl** [comment]
This PR needs to be recreated, as all class methods of PiwikTracker have been moved to MatomoTracker meanwhile

**Pull request closed without merging**
